name: Sync Open-PS2-Loader Fork Daily

on:
  schedule:
    - cron: "0 0 * * *"  # Esegui ogni giorno a mezzanotte (UTC)
  repository_dispatch:
    types: [sync-opl-fork]
  workflow_dispatch:  # Add this line to enable manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permesso per push

    steps:
      - name: Checkout del fork
        uses: actions/checkout@v4
        with:
          ref: master  # Open-PS2-Loader usa "master" come branch principale

      - name: Aggiungi upstream remoto
        run: |
          git remote add upstream https://github.com/ps2homebrew/Open-PS2-Loader.git
          git fetch upstream

      - name: Sincronizza con upstream
        run: |
          git checkout master
          git merge upstream/master
          git push origin master
